[workspace]
allow_dirty = true # allow updating repositories with uncommitted changes
changelog_update = false # disable changelog updates
dependencies_update = true # update dependencies with `cargo update`
git_release_enable = false # disable GitHub/Gitea releases
pr_labels = ["release"] # add the `release` label to the release Pull Request
publish_allow_dirty = false # add `--allow-dirty` to `cargo publish`
semver_check = false # disable API breaking changes checks
publish_timeout = "10m" # set a timeout for `cargo publish`
release_commits = "^feat:" # prepare release only if at least one commit matches a regex

[[package]] # the double square brackets define a TOML table array
name = "popgis"
changelog_update = true # enable changelog update for `popgis`
git_release_enable = true # enable GitHub/Gitea releases for `popgis`
publish = true # disable `cargo publish` for `popgis`

[changelog]
protect_breaking_commits = true # always include commits with breaking changes in the changelog